// Generated by HTMS - CommonJS format
'use strict';

const numbers = [
  10,
  20,
  30
];
const ul1 = document.createElement('ul');
ul1.setAttribute('id', 'numbers');
for (const item of numbers) {
  const li1 = document.createElement('li');
  li1.textContent = `Current number: ${ item }`;
  ul1.appendChild(li1);
}
document.body.appendChild(ul1);