// Generated by HTMS - CommonJS format
'use strict';

let x = 10;
const div1 = document.createElement('div');
div1.setAttribute('id', 'cond');
const p1 = document.createElement('p');
p1.setAttribute('id', 'gt');
p1.textContent = `Greater than 5`;
div1.appendChild(p1);
const p2 = document.createElement('p');
p2.setAttribute('id', 'ngt');
p2.textContent = `Not greater than 5`;
div1.appendChild(p2);
const button1 = document.createElement('button');
button1.setAttribute('id', 'set3');
button1.textContent = `Set x=3`;
div1.appendChild(button1);
const button2 = document.createElement('button');
button2.setAttribute('id', 'set10');
button2.textContent = `Set x=10`;
div1.appendChild(button2);
document.body.appendChild(div1);
function setX(val) {
  try {
    try {
      x = val;
    } catch (error) {
      console.error('Set operation failed:', error);
    }
    (function () {
      try {
        const el = document.querySelector(`#gt`);
        if (!el) {
          console.warn('TOGGLE target not found: #gt');
          return;
        }
        el.style.display = x > 5 ? '' : 'none';
      } catch (error) {
        console.error('TOGGLE failed:', error);
      }
    }());
    (function () {
      try {
        const el = document.querySelector(`#ngt`);
        if (!el) {
          console.warn('TOGGLE target not found: #ngt');
          return;
        }
        el.style.display = x <= 5 ? '' : 'none';
      } catch (error) {
        console.error('TOGGLE failed:', error);
      }
    }());
  } catch (error) {
    console.error('Function setX execution error:', error);
  }
}
try {
  const eventTargets = document.querySelectorAll(`#set3`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #set3');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        setX(3);
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
try {
  const eventTargets = document.querySelectorAll(`#set10`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #set10');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        setX(10);
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
(function () {
  try {
    const el = document.querySelector(`#gt`);
    if (!el) {
      console.warn('TOGGLE target not found: #gt');
      return;
    }
    el.style.display = x > 5 ? '' : 'none';
  } catch (error) {
    console.error('TOGGLE failed:', error);
  }
}());
(function () {
  try {
    const el = document.querySelector(`#ngt`);
    if (!el) {
      console.warn('TOGGLE target not found: #ngt');
      return;
    }
    el.style.display = x <= 5 ? '' : 'none';
  } catch (error) {
    console.error('TOGGLE failed:', error);
  }
}());