// Generated by HTMS - CommonJS format
'use strict';

const button3 = document.createElement('button');
button3.setAttribute('id', 'submitBtn');
button3.textContent = `Submit`;
document.body.appendChild(button3);
const p3 = document.createElement('p');
p3.setAttribute('id', 'msg');
document.body.appendChild(p3);
try {
  const eventTargets = document.querySelectorAll(`#submitBtn`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #submitBtn');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        (function () {
          try {
            const el = document.querySelector(`#msg`);
            if (!el) {
              console.warn('SETPROP target not found: #msg');
              return;
            }
            el['textContent'] = 'Button was clicked!';
          } catch (error) {
            console.error('SETPROP failed:', error);
          }
        }());
        (function () {
          try {
            const el = document.querySelector(`#msg`);
            if (!el) {
              console.warn('SETPROP target not found: #msg');
              return;
            }
            el['style']['color'] = 'green';
          } catch (error) {
            console.error('SETPROP failed:', error);
          }
        }());
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}