// Generated by HTMS - CommonJS format
'use strict';

const outerLoop = [
  1,
  2,
  3
];
const ul3 = document.createElement('ul');
ul3.setAttribute('id', 'nested');
for (const item of outerLoop) {
  const li3 = document.createElement('li');
  const span3 = document.createElement('span');
  span3.textContent = `Outer loop item: ${ item }`;
  li3.appendChild(span3);
  const innerLoop = [
    'a',
    'b',
    'c'
  ];
  const ul4 = document.createElement('ul');
  for (const item of innerLoop) {
    const li4 = document.createElement('li');
    li4.textContent = `Inner loop item: ${ item }`;
    ul4.appendChild(li4);
  }
  li3.appendChild(ul4);
  ul3.appendChild(li3);
}
document.body.appendChild(ul3);