// Generated by HTMS - CommonJS format
'use strict';

const outerLoop = [
  1,
  2,
  3
];
const ul3 = document.createElement('ul');
ul3.setAttribute('id', 'nested');
for (const item of outerLoop) {
  const li2 = document.createElement('li');
  const span2 = document.createElement('span');
  span2.textContent = `Outer loop item: ${ item }`;
  li2.appendChild(span2);
  const innerLoop = [
    'a',
    'b',
    'c'
  ];
  const ul4 = document.createElement('ul');
  for (const item of innerLoop) {
    const li3 = document.createElement('li');
    li3.textContent = `Inner loop item: ${ item }`;
    ul4.appendChild(li3);
  }
  li2.appendChild(ul4);
  ul3.appendChild(li2);
}
document.body.appendChild(ul3);