// Generated by HTMS - CommonJS format
'use strict';

const day = 'Monday';
const div4 = document.createElement('div');
div4.setAttribute('id', 'switchDemo');
switch (day) {
case 'Monday': {
    try {
      const p7 = document.createElement('p');
      p7.textContent = `It's the start of the week.`;
      div4.appendChild(p7);
    } catch (error) {
      console.error('Case execution error:', error);
    }
    break;
  }
default: {
    // Empty default case
    break;
  }
}
document.body.appendChild(div4);