// Generated by HTMS - CommonJS format
'use strict';

const day = 'Monday';
const div3 = document.createElement('div');
div3.setAttribute('id', 'switchDemo');
switch (day) {
case 'Monday': {
    try {
      const p5 = document.createElement('p');
      p5.textContent = `It's the start of the week.`;
      div3.appendChild(p5);
    } catch (error) {
      console.error('Case execution error:', error);
    }
    break;
  }
default: {
    // Empty default case
    break;
  }
}
document.body.appendChild(div3);