// Generated by HTMS - CommonJS format
'use strict';

const day = 'Monday';
const div2 = document.createElement('div');
div2.setAttribute('id', 'switchDemo');
switch (day) {
case 'Monday': {
    try {
      const p4 = document.createElement('p');
      p4.textContent = `It's the start of the week.`;
      div2.appendChild(p4);
    } catch (error) {
      console.error('Case execution error:', error);
    }
    break;
  }
default: {
    // Empty default case
    break;
  }
}
document.body.appendChild(div2);