// Generated by HTMS - CommonJS format
'use strict';

let state = { 'todos': [] };
const div3 = document.createElement('div');
div3.setAttribute('id', 'todoApp');
const h21 = document.createElement('h2');
h21.textContent = `HTMS Todo`;
div3.appendChild(h21);
const input1 = document.createElement('input');
input1.setAttribute('type', 'text');
input1.setAttribute('id', 'newTodo');
input1.setAttribute('placeholder', 'Add a task');
div3.appendChild(input1);
const button4 = document.createElement('button');
button4.setAttribute('id', 'addBtn');
button4.textContent = `Add`;
div3.appendChild(button4);
const ul4 = document.createElement('ul');
ul4.setAttribute('id', 'list');
div3.appendChild(ul4);
document.body.appendChild(div3);
try {
  const eventTargets = document.querySelectorAll(`#addBtn`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #addBtn');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        addTodo();
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
try {
  const eventTargets = document.querySelectorAll(`#newTodo`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #newTodo');
  }
  eventTargets.forEach(element => {
    element.addEventListener('keypress', function (event) {
      try {
        onEnter(event);
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
function onEnter(event) {
  try {
    if (event.key === 'Enter') {
      addTodo();
    }
    // else ignore
    return;
  } catch (error) {
    console.error('Function onEnter execution error:', error);
  }
}
function render() {
  try {
    const list = document.getElementById('list');
    while (list.firstChild)
      list.removeChild(list.firstChild);
    for (let i = 0; i < state.todos.length; i++) {
      const t = state.todos[i];
      const li = document.createElement('li');
      const text = document.createElement('span');
      text.textContent = t;
      const btn = document.createElement('button');
      btn.textContent = '\u2715';
      btn.setAttribute('aria-label', `Remove ${ t }`);
      btn.addEventListener('click', function () {
        try {
          state.todos.splice(i, 1);
          render();
        } catch (error) {
          console.error('Remove todo failed:', error);
        }
      });
      li.appendChild(text);
      li.appendChild(btn);
      list.appendChild(li);
    }
  } catch (error) {
    console.error('Function render execution error:', error);
  }
}
function addTodo() {
  try {
    (function () {
      try {
        state.todos.push(value);
      } catch (error) {
        console.error('PUSH failed:', error);
      }
    }());
    (function () {
      try {
        const el = document.querySelector(`#newTodo`);
        if (!el) {
          console.warn('SETPROP target not found: #newTodo');
          return;
        }
        el['value'] = '';
      } catch (error) {
        console.error('SETPROP failed:', error);
      }
    }());
  } catch (error) {
    console.error('Function addTodo execution error:', error);
  }
}