// Generated by HTMS - CommonJS format
'use strict';

let state = { 'todos': [] };
const div5 = document.createElement('div');
div5.setAttribute('id', 'todoApp');
const input3 = document.createElement('input');
input3.setAttribute('type', 'text');
input3.setAttribute('id', 'newTodo');
input3.setAttribute('placeholder', 'Enter new todo');
div5.appendChild(input3);
const button6 = document.createElement('button');
button6.setAttribute('id', 'addBtn');
button6.textContent = `Add`;
div5.appendChild(button6);
const ul6 = document.createElement('ul');
ul6.setAttribute('id', 'todoList');
div5.appendChild(ul6);
document.body.appendChild(div5);
try {
  const eventTargets = document.querySelectorAll(`#addBtn`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #addBtn');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        addTodo();
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
function addTodo() {
  try {
    const input = document.getElementById('newTodo');
    const value = (input.value || '').trim();
    if (!value)
      return;
    state.todos.push(value);
    input.value = '';
    const li = document.createElement('li');
    li.textContent = value;
    document.getElementById('todoList').appendChild(li);
  } catch (error) {
    console.error('Function addTodo execution error:', error);
  }
}