// Generated by HTMS - CommonJS format
'use strict';

let state = { 'todos': [] };
const div5 = document.createElement('div');
div5.setAttribute('id', 'todoApp');
const h21 = document.createElement('h2');
h21.textContent = `HTMS Todo`;
div5.appendChild(h21);
const input3 = document.createElement('input');
input3.setAttribute('type', 'text');
input3.setAttribute('id', 'newTodo');
input3.setAttribute('placeholder', 'Add a task');
div5.appendChild(input3);
const button7 = document.createElement('button');
button7.setAttribute('id', 'addBtn');
button7.textContent = `Add`;
div5.appendChild(button7);
const ul5 = document.createElement('ul');
ul5.setAttribute('id', 'list');
div5.appendChild(ul5);
document.body.appendChild(div5);
try {
  const eventTargets = document.querySelectorAll(`#addBtn`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #addBtn');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        addTodo();
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
try {
  const eventTargets = document.querySelectorAll(`#newTodo`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #newTodo');
  }
  eventTargets.forEach(element => {
    element.addEventListener('keypress', function (event) {
      try {
        onEnter(event);
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
function onEnter(event) {
  try {
    if (event.key === 'Enter') {
      addTodo();
    }
    // else ignore
    return;
  } catch (error) {
    console.error('Function onEnter execution error:', error);
  }
}
function render() {
  try {
    (function () {
      if (typeof window === 'undefined')
        return;
      if (!window.__htms) {
        window.__htms = {
          watchers: [],
          bind: function () {
          },
          notify: function () {
            this.watchers.forEach(function (w) {
              try {
                const el = document.querySelector(w.sel);
                if (el)
                  el[w.prop] = w.fn();
              } catch (e) {
              }
            });
          }
        };
      }
      if (!window.__htms.keyedList) {
        window.__htms.keyedList = function (sel, arr, render, keyFn) {
          const container = document.querySelector(sel);
          if (!container) {
            console.warn('KEYEDLIST target not found:', sel);
            return;
          }
          const existing = new Map();
          Array.from(container.children).forEach(function (node) {
            const k = node.getAttribute && node.getAttribute('data-key');
            if (k != null)
              existing.set(k, node);
          });
          const used = new Set();
          for (let i = 0; i < arr.length; i++) {
            const item = arr[i];
            const key = String(keyFn(item, i));
            let node = existing.get(key);
            if (!node) {
              node = render(item, i);
              if (node && node.setAttribute)
                node.setAttribute('data-key', key);
            }
            if (node) {
              container.appendChild(node);
              used.add(key);
            }
          }
          existing.forEach(function (node, key) {
            if (!used.has(key)) {
              if (node && node.parentNode === container)
                container.removeChild(node);
            }
          });
        };
      }
    }());
    (function () {
      var __render_item_2 = function (t, i) {
        const li5 = document.createElement('li');
        const span4 = document.createElement('span');
        span4.textContent = `Todo: {t}`;
        li5.appendChild(span4);
        const button8 = document.createElement('button');
        button8.setAttribute('class', 'rm');
        button8.setAttribute('aria-label', 'Remove');
        button8.textContent = `✕`;
        li5.appendChild(button8);
        try {
          const eventTargets = document.querySelectorAll(`.rm`);
          if (eventTargets.length === 0) {
            console.warn('No elements found for event target: .rm');
          }
          eventTargets.forEach(element => {
            element.addEventListener('click', function (event) {
              try {
                try {
                  render();
                } catch (error) {
                  console.error('Function call failed: render', error);
                }
              } catch (error) {
                console.error('Event handler error:', error);
              }
            });
          });
        } catch (error) {
          console.error('Event setup failed:', error);
        }
        return li5;
      };
      var __key_2 = function (t, i) {
        return t;
      };
      if (typeof window !== 'undefined' && window.__htms) {
        window.__htms.keyedList(`#list`, state.todos, __render_item_2, __key_2);
      } else {
        // Fallback: rebuild
        var c = document.querySelector(`#list`);
        if (c) {
          c.textContent = '';
          for (var i = 0; i < state.todos.length; i++) {
            var t = state.todos[i];
            c.appendChild(__render_item_2(t, i));
          }
        }
      }
    }());
  } catch (error) {
    console.error('Function render execution error:', error);
  }
}
function addTodo() {
  try {
    (function () {
      try {
        state.todos.push(document.getElementById('newTodo').value);
      } catch (error) {
        console.error('PUSH failed:', error);
      }
      if (typeof window !== 'undefined' && window.__htms) {
        window.__htms.notify();
      }
    }());
    (function () {
      try {
        const el = document.querySelector(`#newTodo`);
        if (!el) {
          console.warn('SETPROP target not found: #newTodo');
          return;
        }
        el['value'] = '';
      } catch (error) {
        console.error('SETPROP failed:', error);
      }
    }());
  } catch (error) {
    console.error('Function addTodo execution error:', error);
  }
}