// Generated by HTMS - CommonJS format
'use strict';

let state = { 'todos': [] };
const div4 = document.createElement('div');
div4.setAttribute('id', 'todoApp');
const input2 = document.createElement('input');
input2.setAttribute('type', 'text');
input2.setAttribute('id', 'newTodo');
input2.setAttribute('placeholder', 'Enter new todo');
div4.appendChild(input2);
const button5 = document.createElement('button');
button5.setAttribute('id', 'addBtn');
button5.textContent = `Add`;
div4.appendChild(button5);
const ul5 = document.createElement('ul');
ul5.setAttribute('id', 'todoList');
div4.appendChild(ul5);
document.body.appendChild(div4);
try {
  const eventTargets = document.querySelectorAll(`#addBtn`);
  if (eventTargets.length === 0) {
    console.warn('No elements found for event target: #addBtn');
  }
  eventTargets.forEach(element => {
    element.addEventListener('click', function (event) {
      try {
        addTodo();
      } catch (error) {
        console.error('Event handler error:', error);
      }
    });
  });
} catch (error) {
  console.error('Event setup failed:', error);
}
function addTodo() {
  try {
    const input = document.getElementById('newTodo');
    const value = (input.value || '').trim();
    if (!value)
      return;
    state.todos.push(value);
    input.value = '';
    const li = document.createElement('li');
    li.textContent = value;
    document.getElementById('todoList').appendChild(li);
  } catch (error) {
    console.error('Function addTodo execution error:', error);
  }
}